#!/bin/bash
if [ -f "..\pybin\Scripts\activate" ]
then
    # Windows activate python
    source "..\pybin\Scripts\activate"
    python "testapp\githooks\pre_commit.py"
else
    # Linux activate python
    source "..\pybin\bin\activate"
    python "testapp\githooks\pre_commit.py"
fi
